export const BusCity = [
  "Indore, Madhya Pradesh",
  "Vadodara, Gujarat",
  "Varanasi, Uttar Pradesh",
  "Ghaziabad, Uttar Pradesh",
  "Meerut, Uttar Pradesh",
  "Rajkot, Gujarat",
  "Visakhapatnam, Andhra Pradesh",
  "Thane, Maharashtra",
  "Kanpur, Uttar Pradesh",
  "Delhi, National Capital Territory of Delhi",
  "Vijayawada, Andhra Pradesh",
  "Chennai, Tamil Nadu",
  "Hyderabad, Telangana",
  "Pune, Maharashtra",
  "Ahmedabad, Gujarat",
  "Jaipur, Rajasthan",
  "Lucknow, Uttar Pradesh",
  "Pimpri-Chinchwad, Maharashtra",
  "Patna, Bihar",
  "Ludhiana, Punjab",
  "Agra, Uttar Pradesh",
  "Nashik, Maharashtra",
  "Faridabad, Haryana",
  "Kalyan-Dombivali, Maharashtra",
  "Vasai-Virar, Maharashtra",
  "Kolkata, West Bengal",
  "Surat, Gujarat",
  "Srinagar, Jammu and Kashmir",
  "Dhanbad, Jharkhand",
  "Jodhpur, Rajasthan",
  "Coimbatore, Tamil Nadu",
  "Jabalpur, Madhya Pradesh",
  "Gwalior, Madhya Pradesh",
  "Allahabad, Uttar Pradesh",
  "Raipur, Chhattisgarh",
  "Amritsar, Punjab",
];
