export const trainCity = [
  "Delhi Junction",
  "Dhanbad Junction",
  "Surat",
  "Katpadi Junction",
  "Kanpur Central",
  "Kharagpur Junction",
  "Thiruvananthapuram Central",
  "Indore Junction",
  "Chandigarh",
  "Gwalior Junction",
  "Agra Cantonment",
  "Ambala Cantonment",
  "Bhusaval Junction",
  "Manmad Junction",
  "Thrissur",
  "Visakhapatnam Junction",
  "Khurda Road Junction",
  "Ahmedabad Junction",
  "Moradabad Junction",
  "Secunderabad Junction",
  "Nagpur Junction",
  "Howrah Junction",
  "Mysuru Junction",
  "Amritsar Junction",
  "Pune Junction",
  "Raipur Junction",
  "New Delhi",
  "Jhansi Junction",
  "Varanasi Junction",
  "Guwahati",
  "Asansol Junction",
  "Nadiad Junction",
  "Bhopal Junction",
  "Yesvantpur Junction",
  "Kollam Junction",
  "Ludhiana Junction",
  "Bengaluru Cantt",
  "Vijayawada Junction",
  "Warangal",
  "Anand Junction",
  "Hubli Junction",
  "Jodhpur Junction",
];
